### ISSUE TITLE
Compiling UrhoBotTest project with Urho3D v1.5

### ISSUE THREAD

**Issue by valera-rozuvan** [MonkeyFirst/UrhoBotTest#1]
Hey @MonkeyFirst !

Great, great example project = ) I saw your video at https://www.youtube.com/watch?v=yNIsJa_RqB8 and decided to try and compile your code with the new Urho3D version 1.5. However, I am running into some issues.

My work in progress at converting your code to use Urho3D 1.5 is here: https://github.com/valera-rozuvan/UrhoBotTest/tree/migrate_to_urho3d_1_5 . It compiles, and runs - but the result is not what you expect = )

I started a discussion thread here http://urho3d.prophpbb.com/topic1780.html to try and get some help from other Urho3D community users.

Can you please help me migrate your example to use Urho3D version 1.5?

**Comment by valera-rozuvan** [comment]
@MonkeyFirst I figured out what was wrong = ) Pushed my fix to https://github.com/valera-rozuvan/UrhoBotTest/tree/migrate_to_urho3d_1_5 . Are you interested in merging my changes into your repository?

**Comment by valera-rozuvan** [comment]
Just in case: PR https://github.com/MonkeyFirst/UrhoBotTest/pull/2 = )

**Comment by MonkeyFirst** [comment]
Hi, @valera-rozuvan. You probably just copy old shaders into new Urho3D 1.5 bin...

> Are you interested in merging my changes into your repository?

Thanks, but example already migrated to 1.5.

**Comment by valera-rozuvan** [comment]
OK.
